[theme]
base = "light"
primaryColor = "#196c50"
backgroundColor = "#f3f5f0"
secondaryBackgroundColor = "#ffffff"
textColor = "#183d35"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
